# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install --user -r requirements.txt

      - run:
          name: run tests
          command: |
            python tests.py

  dockerize:
   machine: true
   working_directory: ~/repo
   steps:
     # Login to docker
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t $DOCKER_USER/myapp-project:$CIRCLE_SHA1 .

     # deploy the image
     - run: docker push $DOCKER_USER/myapp-project:$CIRCLE_SHA1    


  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: Save the sshkey
          command: |
            echo $sshkey > key
      - run:
          name: chmod the key
          command: |
            chmod 400 key
      - run:
          name: stop the old, pull and start the new docker image
          command: |
            ssh -i key ubuntu@ipadr "docker stop myapp-project ; docker pull $DOCKER_USER/myapp-project ; docker run -d myapp-project"

workflows:
  version: 2
  build-dockerize-and-deploy:
    jobs:
      - build
      - dockerize:
          requires:
            - build
      - deploy:
          requires:
            - dockerize
          filters:
            branches:
              only: sequential-branch-filter

